# Generated by Django 3.1.4 on 2021-03-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210303_0422'),
        ('blogs', '0003_auto_20210307_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseeker_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('Web Development', 'Web Development'), ('Communication', 'Communication'), ('Marketing', 'Marketing'), ('Photoshop', 'Photoshop'), ('Php', 'Php'), ('Accounting', 'Accounting'), ('Css', 'Css'), ('Data Analysis', 'Data Analysis')], max_length=100)),
                ('jobseeker_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker_language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('English', 'English'), ('Nepali', 'Nepali'), ('Hindi', 'Hindi'), ('Korean', 'Korean'), ('Japanese', 'Japanese')], max_length=100)),
                ('jobseeker_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker_employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('jobseeker_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker_education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=150, null=True)),
                ('high_school', models.CharField(blank=True, max_length=150, null=True)),
                ('degree', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('jobseeker_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker')),
            ],
        ),
    ]
