# Generated by Django 3.1.4 on 2021-03-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20210307_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_profile',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
