# Generated by Django 3.1.4 on 2021-03-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210307_2041'),
        ('blogs', '0006_employer_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker_language',
            name='jobseeker_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker'),
        ),
    ]
