# Generated by Django 3.1.4 on 2021-03-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employer_company_name'),
        ('blogs', '0009_auto_20210309_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobseeker_Skill',
            new_name='Skill',
        ),
    ]
