# Generated by Django 3.1.4 on 2021-03-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20210309_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(blank=True, choices=[('Web Development', 'Web Development'), ('Communication', 'Communication'), ('Marketing', 'Marketing'), ('Photoshop', 'Photoshop'), ('Php', 'Php'), ('Accounting', 'Accounting'), ('Css', 'Css'), ('Data Analysis', 'Data Analysis')], max_length=100),
        ),
    ]
