# Generated by Django 3.1.4 on 2021-03-02 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_jobseeker', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('job_category', models.CharField(choices=[('Construction/Engineering', 'Construction/Engineering'), ('Create/Graphic', 'Create/Graphic'), ('Teaching/Education', 'Teaching/Education'), ('Hospitality', 'Hospitality'), ('Marketing/Advertising', 'Marketing/Advertising'), ('Accounting/Finance', 'Accounting/Finance'), ('IT & Communication', 'IT & Communication')], default=None, max_length=150)),
                ('token', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_employer', models.BooleanField(default=False)),
                ('industry_type', models.CharField(choices=[('Manufacturing/Engineering', 'Manufacturing/Engineering'), ('Advertising Agency', 'Advertising Agency'), ('Banks', 'Banks'), ('Education', 'Education'), ('Information/Computer', 'Information/Computer'), ('Finances Companies', 'Finances Companies'), ('E-commerce/E-business', 'E-commerce/E-business')], default='None', max_length=150, null=True)),
                ('token', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
