# Generated by Django 3.1.4 on 2021-03-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='job_category',
            field=models.CharField(choices=[('Construction/Engineering', 'Construction/Engineering'), ('Create/Graphic', 'Create/Graphic'), ('Teaching/Education', 'Teaching/Education'), ('Hospitality', 'Hospitality'), ('Marketing/Advertising', 'Marketing/Advertising'), ('Accounting/Finance', 'Accounting/Finance'), ('IT & Communication', 'IT & Communication')], default=None, max_length=150, null=True),
        ),
    ]
