# Generated by Django 3.1.4 on 2021-03-02 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210302_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
    ]
