# Generated by Django 3.1.4 on 2021-03-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210303_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='industry_type',
            field=models.CharField(choices=[('Select One', 'Select One'), ('Manufacturing/Engineering', 'Manufacturing/Engineering'), ('Advertising Agency', 'Advertising Agency'), ('Banks', 'Banks'), ('Education', 'Education'), ('Information/Computer', 'Information/Computer'), ('Finances Companies', 'Finances Companies'), ('E-commerce/E-business', 'E-commerce/E-business')], default='None', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='job_category',
            field=models.CharField(choices=[('Select One', 'Select One'), ('Construction/Engineering', 'Construction/Engineering'), ('Create/Graphic', 'Create/Graphic'), ('Teaching/Education', 'Teaching/Education'), ('Hospitality', 'Hospitality'), ('Marketing/Advertising', 'Marketing/Advertising'), ('Accounting/Finance', 'Accounting/Finance'), ('IT & Communication', 'IT & Communication')], default='None', max_length=150, null=True),
        ),
    ]
