# Generated by Django 3.1.4 on 2021-03-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210307_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_name',
            field=models.CharField(default=False, max_length=150),
        ),
    ]
